version: "3"

services:

  environment:
    - version=00

  teste:
    image: 2agcloud/ubuntu-base:${version}
    network_mode: "bridge"
    ports:
      - "9121:9121"
    container_name: "testeooooo"
