name: CI - deevelopment teste

# Deve ser executado ao ocorrer um "push" ou "PR" na main
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Já apenas um job que é executado em uma insância do ubuntu
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    steps:
      # TESTE 
      - name: Teste de Variavel
        uses: actions/checkout@master
        with:
           echo "${{ github.run_number }}"         
