name: CI - deevelopment teste

# Deve ser executado ao ocorrer um "push" ou "PR" na main
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Já apenas um job que é executado em uma insância do ubuntu
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    steps:
      # TESTE 
      - name: Teste de Variavel
        run: echo "${{ github.run_number }}" >> .env_version
      - name: Ver o arquivo
        run: ls -Alh
      - name: Ver dentro do arquivo
        run: cat .env_version
   #  - name: Subir arquivo para branch
   #    run: git diff a/.env_version b/.env_version
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.AC_DOCKER_HUB_USERNAME }} # O segredo deve exisitr
          password: ${{ secrets.AC_DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build and push Docker images
        uses: docker/build-push-action@v2.3.0
        with:
          # Contexto onde está o arquivo Dockerfile, normalmente é .
          context: .
          # Qual a tag
          tags: 2agcloud/teste:${{ github.run_number }}
          no-cache: true
          push: true
  docker:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Start containers
      run: docker-compose -f "docker-compose.yml" up -d --build
      
    - name: Stop containers
      if: always()
      run: docker-compose -f "docker-compose.yml" down

