name: CI - deevelopment teste

# Deve ser executado ao ocorrer um "push" ou "PR" na main
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Já apenas um job que é executado em uma insância do ubuntu
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    steps:
      # TESTE 
      - name: Teste de Variavel
        run: echo "${{ github.run_number }}" >> .env_version
      - name: Ver o arquivo
        run: ls -Alh
      - name: Ver dentro do arquivo
        run: cat .env_version
   #  - name: Subir arquivo para branch
   #    run: git diff a/.env_version b/.env_version
  docker:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
      
    - name: Ver o arquivo docker
      run: ls -Al 
      
    - name: Preparando arquivo docker-compose.yml
      run: rm -Rf docker-compose.yml && cp ./deploy.conf/docker-compose-base.yml ./docker-compose.yml && sed -i 's/version=00/version="${{ github.run_number }}"/g' ./docker-compose.yml && more docker-compose.yml 
    - name: Atualizando o docker-compose no git
      run: git config --global user.name "Supote 2AG" && git config --global user.email "suporte@grupo2ag.com.br" && git config --global user.password "${{ secrets.PASSWORD }}" && git checkout main && git add -f -- docker-compose.yml  && git commit -m "Atualização docker-compose" && git push -u https://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@github.com/grupo2ag/dck-ssl-sites-traefik.git main && git status 

   
